import = ["~/.config/alacritty/catppuccin/catppuccin-macchiato.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[selection]
save_to_clipboard = true

[window]
dynamic_title = false
startup_mode = "Maximized"
title = "Alacritty"
